name: Generate Terraform docs

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  docs:
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'release-please--') }}
    # Set the agent to run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0
        with:
          git-push: "true"
          output-file: "README.md"
          output-format: markdown document
          output-method: "inject"
          working-dir: .
